### ISSUE TITLE
Typo in the FAQ section

### ISSUE THREAD

**Issue by edward-hong** [bluebill1049/react-hook-form-website#5]
Hi, I noticed that there's a typo on the last FAQ question "What if you don't have access to ref?". In the code block, you're importing `useRef` instead of `useEffect`.

**Comment by bluebill1049** [comment]
thanks @edward-hong ❤️ would you like to submit a PR?

**Comment by bluebill1049** [comment]
thanks for reporting :) i have fixed the issue 🥃
